
  mdb-db:
    image: postgres:14
    container_name: mdb-db
    ports:
      - "5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: mdb_database
    volumes:
      - ../../../esb-mdb/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql
