
  esb-mdb-native:
    image: quay.io/quarkus-esb-reactive/esb-mdb:native-latest
    container_name: esb-mdb-native
    depends_on:
      - mdb-db
    ports:
      - "8083:8083"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://mdb-db:5432/mdb_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      QUARKUS_DATASOURCE_USERNAME: superman
      QUARKUS_DATASOURCE_PASSWORD: superman
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
      QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    restart: on-failure
    networks:
      default:
        aliases:
          - esb-mdb
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
